# name: Swiggy-Frontend

# on:
#   push:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ['self-hosted', 'Linux', 'X64' ]

    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build


name: CI/CD

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          S3_BUCKET_NAME: react-assets-bucket
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete

